In [1]:
import numpy as np

In [ ]:
#why is numpy faster than lists?
#looks at it as binary list
#normal list will have size, ref count, obj type, obj value
#FASTER TO READ LESS BYTES OF MEMORY
#CONTIGUOUS MEMORY

In [16]:
a = np.array([1,2,3],dtype = 'int32')
a

array([1, 2, 3], dtype=int32)

In [4]:
b = np.array([[4,5,6,],[7.0,8.0,9.0]])
b

array([[4., 5., 6.],
       [7., 8., 9.]])

In [8]:
#get dimensions on np araay
a.ndim, b.ndim

(1, 2)

In [13]:
a.shape, b.shape

((3,), (2, 3))

In [12]:
a.dtype, b.dtype

(dtype('int64'), dtype('float64'))

In [19]:
#get size, total number of elements
a.itemsize, b.itemsize

(4, 8)

In [21]:
#get total size
a.nbytes, b.nbytes

(12, 48)

In [22]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
c.shape

(2, 7)

In [27]:
#get specific index [r,c]
c[1,5] #13
#c[1,-2]

13

In [29]:
#get specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#specific column
c[:,0]

array([1, 8])

In [41]:
#[start index: end index: step size]
c[0, 1:-1:2]

array([2, 4, 6])

In [46]:
c[1,5]=20
c

array([[ 5,  5,  1,  5,  5,  5,  5],
       [ 5,  5,  2,  5,  5, 20,  5]])

In [47]:
#get specific element
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [50]:
#3D array selectting element (work outside in)
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [52]:
###INITIALIZE DIFFERENT TYPES OF ARRAYS
#all 0's
np.zeros((2,2,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [53]:
#all 1's
np.ones((4,2,2),dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [54]:
#any other number
np.full((2,2),55)

array([[55, 55],
       [55, 55]])

In [58]:
#full like
np.full_like(a,4)#takes a.shape

array([4, 4, 4], dtype=int32)

In [59]:
#random decimals
np.random.rand(4,2)#pass in shape

array([[0.02951815, 0.65338767],
       [0.84996806, 0.27364435],
       [0.42611836, 0.19379298],
       [0.18424863, 0.43941209]])

In [80]:
#random ints
np.random.randint(4,7,size = (3,3))#start value 0-> x, or set bounds

array([[6, 5, 4],
       [4, 4, 4],
       [4, 5, 6]])

In [85]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
arr = np.array([1,2,3])
r1=np.repeat(arr,4)
r1

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [97]:
#cool shape 
out = np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
out[1:-1,1:-1]=z
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [107]:
a = np.array([1,2,3])
#b=a
b=a.copy()
b[1]=100

a

array([1, 2, 3])

In [108]:
###MATHEMATICS
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [110]:
a+2
#a*2
#a/2
#a-2

array([3, 4, 5, 6])

In [112]:
b = np.array([1,0,1,0])
c = a+b
c

array([2, 2, 4, 4])

In [114]:
np.cos(a)
#sin, tan, etc...

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
###LINEAR ALGEBRA
a= np.ones((2,3))
b= np.full((3,2),2)
a , b 

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2, 2],
        [2, 2],
        [2, 2]]))

In [119]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [121]:
c = np.identity(3)
np.linalg.det(c)
#lot to do with lin alg with np

1.0

In [132]:
###STATISTICS
a = np.array([[1,2,3],[4,5,6]])
np.min(a,axis=1), np.max(a,axis = 1), np.sum(a, axis=1)

(array([1, 4]), array([3, 6]), array([ 6, 15]))

In [137]:
###Reorganizing arrays
b = np.array([[1,2,3,4],[5,6,7,8]])

a = b.reshape(2,2,2)
c = b.reshape(2,4)

a,c

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [143]:
###VERTTICAL STACKING VECTORS
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,[9,10,11,12],np.ones(4)])

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [ 1.,  1.,  1.,  1.]])

In [146]:
###HORRIZONTAL STACKING VECTORS
v1 = np.ones((2,4))
v2 = np.zeros((2,2))

np.hstack([v1,v2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [150]:
###LOAD DATA FROM FILE
file = np.genfromtxt('data.txt',delimiter = ',')
file = file.astype('int32')#save as int, must copy to new file
file

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [151]:
###BOOLEAN MASKING AND ADVANCED INDEXING
file>50
#file = 50, etc

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [152]:
file[file>50]
#can index with a list in numpy

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [153]:
np.any(file>50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])